### ISSUE TITLE
Estimating speed of moving objects while ego vehicle is in motion too

### ISSUE THREAD

**Issue by Rak-r** [porscheofficial/speed-estimation-traffic-monitoring#16]
I have set up the detection and tracking for my robot which uses RGB-D camera to get video streams. I am using YOLOV8 for detection and tracking using DEEPSORT. This whole stack is working on my robot. I want o estimate the speed of detected objects particularly Pedestrians when my robot is also in motion. I know I can implement relative velocity concept but need more guidance an dhow can I use this repo with my stack.

I am bit new to this, so any help would be appreciated.

**Comment by matsch845** [comment]
Hi @Rak-r,

sorry for the late reply.
The thing is that this repo is for static cameras that don't move themselves, which means that the pipeline calibrates itself first and then estimates the speed of the objects. In your case, the camera would be constantly moving, which makes it difficult for the pipeline to calibrate properly. So you would need to implement additional logic that works with a moving camera.
Have you made any progress so far?

Kind regards
Matthias
