### ISSUE TITLE
More of a question than an issue

### ISSUE THREAD

**Issue by skoghan** [porscheofficial/speed-estimation-traffic-monitoring#8]
@matsch845, and @pboes,

I noticed in the instructions under **RUN**. That the dataset appears to process only previously saved video. (The path to the video should be given to speed_estimation/speed_estimation.py as argument)

Is there anyway to run your code with live video? Possibly capture and save the video segment of offenders going over the speed limit by 20mphs as an example?

First time on Github, so my appologies if I missed something that refrences processing live video.

Additionally this is an awesome project! Thank you!

**Comment by matsch845** [comment]
Hello @skoghan 
thank you for your interest in our repository!

You're right, we've been focusing more on pre-recorded videos for now.
Nonetheless, we have started to use our pipeline for streaming videos, but that is still a work in progress. You can check out the `speed_estimation/modules/streaming/stream_video.py` file where we started working on the issue you mentioned. With the current state, you are able to stream a video, but this module is not yet integrated into the pipeline.
So if you want, feel free to go ahead and make the speed estimation pipeline work with video streams as well 😊.

**Comment by skoghan** [comment]
Hi @matsch845, Thanks for the kind response and explination. Unfortuantly I do not have any coding skills. I am in the process of learning OpenCV. It's going ot be a while untill I can catribute.  My specific use case is somewhat unique and the ability to get the speed in an un calibrated video is really useful. I would be streaming via RTSP protocol. If possible is there a way we can take this conversation offline to discuss and see if we can come up with some solution for the stream portion of this project. 

Much appreciated!

**Comment by matsch845** [comment]
Hi @skoghan,
sorry for the late response. Yes sure, let's take this conversation offline. As a starting point you can contact me at the email address **matthias.schneider@porsche.digital**.
Looking forward to hearing form you! :)

**Comment by matsch845** [comment]
Since this issue will be further discussed offline, I close it.
